import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


import { initializeCron } from "@/lib/cron";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Online Store",
  description: "Generated by create next app",
};

// Initialize cron jobs when the app starts
if (typeof window === 'undefined') {
  initializeCron();
}

import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
import { prisma } from "@/lib/prisma";

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // Fetch background image URL from settings
  let bgImageUrl = ''
  try {
    const bgImageSetting = await prisma.settings.findUnique({
      where: { key: 'backgroundImageUrl' }
    })
    bgImageUrl = bgImageSetting?.value || ''
  } catch (error) {
    console.warn('Failed to fetch background image setting:', error)
  }

  const bgStyle = bgImageUrl ? `url(${bgImageUrl})` : undefined

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={inter.className}
        style={{
          display: 'flex',
          flexDirection: 'column',
          minHeight: '100vh',
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          ...(bgStyle && { '--bg-image': bgStyle } as any)
        }}
      >
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
